package empprofile;


import com.sun.org.apache.xerces.internal.parsers.XMLParser;
import com.sun.org.apache.xml.internal.serialize.OutputFormat;
import com.sun.org.apache.xml.internal.serialize.XMLSerializer;
import java.io.FileOutputStream;
import javax.xml.parsers.SAXParserFactory;
import org.xml.sax.Attributes;
import org.xml.sax.ContentHandler;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.AttributesImpl;
import org.xml.sax.helpers.DefaultHandler;

/**
 * ProfileBySAX uses a ContentHandler to write the profile to an XML File.
 * The ContantHandler is passed to objects of inner classes that extend from DefaulHandler.
 * These classes write elements and attributes to the ContentHandler as events are generated by the SAX parser. 
 * 
 */
public class SAXParser {


    public static void main(String[] args) {

        try {
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }


    static class MyParser extends DefaultHandler {

        
        public MyParser() {
        
        }}

        

}


