//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.29 at 06:41:16 AM CST 
//


package generate;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="companies">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="company" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="companyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="founders" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ceo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="contact" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "companies"
})
@XmlRootElement(name = "companyInfo", namespace = "http://namespace.profile.com/ns/com")
public class CompanyInfo {

    @XmlElement(namespace = "http://namespace.profile.com/ns/com", required = true)
    protected CompanyInfo.Companies companies;

    /**
     * Gets the value of the companies property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyInfo.Companies }
     *     
     */
    public CompanyInfo.Companies getCompanies() {
        return companies;
    }

    /**
     * Sets the value of the companies property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyInfo.Companies }
     *     
     */
    public void setCompanies(CompanyInfo.Companies value) {
        this.companies = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="company" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="companyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="founders" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ceo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="contact" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "company"
    })
    public static class Companies {

        @XmlElement(namespace = "http://namespace.profile.com/ns/com", required = true)
        protected List<CompanyInfo.Companies.Company> company;

        /**
         * Gets the value of the company property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the company property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCompany().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CompanyInfo.Companies.Company }
         * 
         * 
         */
        public List<CompanyInfo.Companies.Company> getCompany() {
            if (company == null) {
                company = new ArrayList<CompanyInfo.Companies.Company>();
            }
            return this.company;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="companyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="founders" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ceo" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="contact" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "companyId",
            "companyName",
            "category",
            "founders",
            "ceo",
            "location",
            "contact"
        })
        public static class Company {

            @XmlElement(namespace = "http://namespace.profile.com/ns/com", required = true)
            protected String companyId;
            @XmlElement(namespace = "http://namespace.profile.com/ns/com", required = true)
            protected String companyName;
            @XmlElement(namespace = "http://namespace.profile.com/ns/com", required = true)
            protected String category;
            @XmlElement(namespace = "http://namespace.profile.com/ns/com", required = true)
            protected String founders;
            @XmlElement(namespace = "http://namespace.profile.com/ns/com", required = true)
            protected String ceo;
            @XmlElement(namespace = "http://namespace.profile.com/ns/com", required = true)
            protected String location;
            @XmlElement(namespace = "http://namespace.profile.com/ns/com", required = true)
            protected String contact;

            /**
             * Gets the value of the companyId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCompanyId() {
                return companyId;
            }

            /**
             * Sets the value of the companyId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCompanyId(String value) {
                this.companyId = value;
            }

            /**
             * Gets the value of the companyName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCompanyName() {
                return companyName;
            }

            /**
             * Sets the value of the companyName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCompanyName(String value) {
                this.companyName = value;
            }

            /**
             * Gets the value of the category property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCategory() {
                return category;
            }

            /**
             * Sets the value of the category property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCategory(String value) {
                this.category = value;
            }

            /**
             * Gets the value of the founders property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFounders() {
                return founders;
            }

            /**
             * Sets the value of the founders property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFounders(String value) {
                this.founders = value;
            }

            /**
             * Gets the value of the ceo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCeo() {
                return ceo;
            }

            /**
             * Sets the value of the ceo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCeo(String value) {
                this.ceo = value;
            }

            /**
             * Gets the value of the location property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocation() {
                return location;
            }

            /**
             * Sets the value of the location property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocation(String value) {
                this.location = value;
            }

            /**
             * Gets the value of the contact property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContact() {
                return contact;
            }

            /**
             * Sets the value of the contact property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContact(String value) {
                this.contact = value;
            }

        }

    }

}
