//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.29 at 06:41:16 AM CST 
//


package generate;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="empName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="companyWorked" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="workedAtComId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="workedAt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "empName",
    "companyWorked"
})
@XmlRootElement(name = "empRecord", namespace = "http://namespace.profile.com/ns/empRecord")
public class EmpRecord {

    @XmlElement(namespace = "http://namespace.profile.com/ns/empRecord", required = true)
    protected String empName;
    @XmlElement(namespace = "http://namespace.profile.com/ns/empRecord")
    protected List<EmpRecord.CompanyWorked> companyWorked;

    /**
     * Gets the value of the empName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * Sets the value of the empName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpName(String value) {
        this.empName = value;
    }

    /**
     * Gets the value of the companyWorked property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the companyWorked property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompanyWorked().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EmpRecord.CompanyWorked }
     * 
     * 
     */
    public List<EmpRecord.CompanyWorked> getCompanyWorked() {
        if (companyWorked == null) {
            companyWorked = new ArrayList<EmpRecord.CompanyWorked>();
        }
        return this.companyWorked;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="workedAtComId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="workedAt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "workedAtComId",
        "workedAt",
        "duration",
        "year",
        "position"
    })
    public static class CompanyWorked {

        @XmlElement(namespace = "http://namespace.profile.com/ns/empRecord", required = true)
        protected String workedAtComId;
        @XmlElement(namespace = "http://namespace.profile.com/ns/empRecord", required = true)
        protected String workedAt;
        @XmlElement(namespace = "http://namespace.profile.com/ns/empRecord", required = true)
        protected String duration;
        @XmlElement(namespace = "http://namespace.profile.com/ns/empRecord")
        protected int year;
        @XmlElement(namespace = "http://namespace.profile.com/ns/empRecord", required = true)
        protected String position;

        /**
         * Gets the value of the workedAtComId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWorkedAtComId() {
            return workedAtComId;
        }

        /**
         * Sets the value of the workedAtComId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWorkedAtComId(String value) {
            this.workedAtComId = value;
        }

        /**
         * Gets the value of the workedAt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWorkedAt() {
            return workedAt;
        }

        /**
         * Sets the value of the workedAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWorkedAt(String value) {
            this.workedAt = value;
        }

        /**
         * Gets the value of the duration property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDuration() {
            return duration;
        }

        /**
         * Sets the value of the duration property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDuration(String value) {
            this.duration = value;
        }

        /**
         * Gets the value of the year property.
         * 
         */
        public int getYear() {
            return year;
        }

        /**
         * Sets the value of the year property.
         * 
         */
        public void setYear(int value) {
            this.year = value;
        }

        /**
         * Gets the value of the position property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPosition() {
            return position;
        }

        /**
         * Sets the value of the position property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPosition(String value) {
            this.position = value;
        }

    }

}
