//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.29 at 06:41:16 AM CST 
//


package generate;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generate package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generate
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link generate.CompanyInfo }
     * 
     */
    public generate.CompanyInfo createCompanyInfo() {
        return new generate.CompanyInfo();
    }

    /**
     * Create an instance of {@link generate.EmpRecord }
     * 
     */
    public generate.EmpRecord createEmpRecord() {
        return new generate.EmpRecord();
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link generate.Transcript }
     * 
     */
    public generate.Transcript createTranscript() {
        return new generate.Transcript();
    }

    /**
     * Create an instance of {@link generate.Transcript.Courses }
     * 
     */
    public generate.Transcript.Courses createTranscriptCourses() {
        return new generate.Transcript.Courses();
    }

    /**
     * Create an instance of {@link Profile.Transcript }
     * 
     */
    public Profile.Transcript createProfileTranscript() {
        return new Profile.Transcript();
    }

    /**
     * Create an instance of {@link Profile.Transcript.Courses }
     * 
     */
    public Profile.Transcript.Courses createProfileTranscriptCourses() {
        return new Profile.Transcript.Courses();
    }

    /**
     * Create an instance of {@link Profile.CompanyInfo }
     * 
     */
    public Profile.CompanyInfo createProfileCompanyInfo() {
        return new Profile.CompanyInfo();
    }

    /**
     * Create an instance of {@link Profile.CompanyInfo.Companies }
     * 
     */
    public Profile.CompanyInfo.Companies createProfileCompanyInfoCompanies() {
        return new Profile.CompanyInfo.Companies();
    }

    /**
     * Create an instance of {@link Profile.EmpRecord }
     * 
     */
    public Profile.EmpRecord createProfileEmpRecord() {
        return new Profile.EmpRecord();
    }

    /**
     * Create an instance of {@link generate.CompanyInfo.Companies }
     * 
     */
    public generate.CompanyInfo.Companies createCompanyInfoCompanies() {
        return new generate.CompanyInfo.Companies();
    }

    /**
     * Create an instance of {@link Cv }
     * 
     */
    public Cv createCv() {
        return new Cv();
    }

    /**
     * Create an instance of {@link generate.EmpRecord.CompanyWorked }
     * 
     */
    public generate.EmpRecord.CompanyWorked createEmpRecordCompanyWorked() {
        return new generate.EmpRecord.CompanyWorked();
    }

    /**
     * Create an instance of {@link Profile.CvInfo }
     * 
     */
    public Profile.CvInfo createProfileCvInfo() {
        return new Profile.CvInfo();
    }

    /**
     * Create an instance of {@link generate.Transcript.Courses.Course }
     * 
     */
    public generate.Transcript.Courses.Course createTranscriptCoursesCourse() {
        return new generate.Transcript.Courses.Course();
    }

    /**
     * Create an instance of {@link Profile.Transcript.Courses.Course }
     * 
     */
    public Profile.Transcript.Courses.Course createProfileTranscriptCoursesCourse() {
        return new Profile.Transcript.Courses.Course();
    }

    /**
     * Create an instance of {@link Profile.CompanyInfo.Companies.Company }
     * 
     */
    public Profile.CompanyInfo.Companies.Company createProfileCompanyInfoCompaniesCompany() {
        return new Profile.CompanyInfo.Companies.Company();
    }

    /**
     * Create an instance of {@link Profile.EmpRecord.CompanyWorked }
     * 
     */
    public Profile.EmpRecord.CompanyWorked createProfileEmpRecordCompanyWorked() {
        return new Profile.EmpRecord.CompanyWorked();
    }

    /**
     * Create an instance of {@link generate.CompanyInfo.Companies.Company }
     * 
     */
    public generate.CompanyInfo.Companies.Company createCompanyInfoCompaniesCompany() {
        return new generate.CompanyInfo.Companies.Company();
    }

}
