//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.29 at 06:41:16 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://namespace.profile.com/ns/transcript", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package generate;
