//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.29 at 06:41:16 AM CST 
//


package generate;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cv_info">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="telephone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="education" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="qualifications" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="jobType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="desiredPosition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="references" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="motivation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="empRecord">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="empName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="companyWorked" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="workedAtComId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="workedAt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="companyInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="companies">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="company" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="companyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="founders" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ceo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="contact" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="transcript">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="studentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="university" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="program" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="issueDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="gpa" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                   &lt;element name="courses">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="course" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="code">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;pattern value="[A-Z][A-Z][0-9][0-9][0-9][0-9]"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="credits" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                       &lt;element name="grade" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cvInfo",
    "empRecord",
    "companyInfo",
    "transcript"
})
@XmlRootElement(name = "profile", namespace = "http://namespace.profile.com/ns/profile")
public class Profile {

    @XmlElement(name = "cv_info", namespace = "http://namespace.profile.com/ns/profile", required = true)
    protected Profile.CvInfo cvInfo;
    @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
    protected Profile.EmpRecord empRecord;
    @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
    protected Profile.CompanyInfo companyInfo;
    @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
    protected Profile.Transcript transcript;

    /**
     * Gets the value of the cvInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Profile.CvInfo }
     *     
     */
    public Profile.CvInfo getCvInfo() {
        return cvInfo;
    }

    /**
     * Sets the value of the cvInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Profile.CvInfo }
     *     
     */
    public void setCvInfo(Profile.CvInfo value) {
        this.cvInfo = value;
    }

    /**
     * Gets the value of the empRecord property.
     * 
     * @return
     *     possible object is
     *     {@link Profile.EmpRecord }
     *     
     */
    public Profile.EmpRecord getEmpRecord() {
        return empRecord;
    }

    /**
     * Sets the value of the empRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link Profile.EmpRecord }
     *     
     */
    public void setEmpRecord(Profile.EmpRecord value) {
        this.empRecord = value;
    }

    /**
     * Gets the value of the companyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Profile.CompanyInfo }
     *     
     */
    public Profile.CompanyInfo getCompanyInfo() {
        return companyInfo;
    }

    /**
     * Sets the value of the companyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Profile.CompanyInfo }
     *     
     */
    public void setCompanyInfo(Profile.CompanyInfo value) {
        this.companyInfo = value;
    }

    /**
     * Gets the value of the transcript property.
     * 
     * @return
     *     possible object is
     *     {@link Profile.Transcript }
     *     
     */
    public Profile.Transcript getTranscript() {
        return transcript;
    }

    /**
     * Sets the value of the transcript property.
     * 
     * @param value
     *     allowed object is
     *     {@link Profile.Transcript }
     *     
     */
    public void setTranscript(Profile.Transcript value) {
        this.transcript = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="companies">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="company" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="companyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="founders" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ceo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="contact" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "companies"
    })
    public static class CompanyInfo {

        @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
        protected Profile.CompanyInfo.Companies companies;

        /**
         * Gets the value of the companies property.
         * 
         * @return
         *     possible object is
         *     {@link Profile.CompanyInfo.Companies }
         *     
         */
        public Profile.CompanyInfo.Companies getCompanies() {
            return companies;
        }

        /**
         * Sets the value of the companies property.
         * 
         * @param value
         *     allowed object is
         *     {@link Profile.CompanyInfo.Companies }
         *     
         */
        public void setCompanies(Profile.CompanyInfo.Companies value) {
            this.companies = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="company" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="companyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="founders" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ceo" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="contact" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "company"
        })
        public static class Companies {

            @XmlElement(namespace = "http://namespace.profile.com/ns/profile")
            protected List<Profile.CompanyInfo.Companies.Company> company;

            /**
             * Gets the value of the company property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the company property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCompany().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Profile.CompanyInfo.Companies.Company }
             * 
             * 
             */
            public List<Profile.CompanyInfo.Companies.Company> getCompany() {
                if (company == null) {
                    company = new ArrayList<Profile.CompanyInfo.Companies.Company>();
                }
                return this.company;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="companyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="founders" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ceo" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="contact" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "companyId",
                "companyName",
                "category",
                "founders",
                "ceo",
                "location",
                "contact"
            })
            public static class Company {

                @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
                protected String companyId;
                @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
                protected String companyName;
                @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
                protected String category;
                @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
                protected String founders;
                @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
                protected String ceo;
                @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
                protected String location;
                @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
                protected String contact;

                /**
                 * Gets the value of the companyId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCompanyId() {
                    return companyId;
                }

                /**
                 * Sets the value of the companyId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCompanyId(String value) {
                    this.companyId = value;
                }

                /**
                 * Gets the value of the companyName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCompanyName() {
                    return companyName;
                }

                /**
                 * Sets the value of the companyName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCompanyName(String value) {
                    this.companyName = value;
                }

                /**
                 * Gets the value of the category property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCategory() {
                    return category;
                }

                /**
                 * Sets the value of the category property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCategory(String value) {
                    this.category = value;
                }

                /**
                 * Gets the value of the founders property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFounders() {
                    return founders;
                }

                /**
                 * Sets the value of the founders property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFounders(String value) {
                    this.founders = value;
                }

                /**
                 * Gets the value of the ceo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCeo() {
                    return ceo;
                }

                /**
                 * Sets the value of the ceo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCeo(String value) {
                    this.ceo = value;
                }

                /**
                 * Gets the value of the location property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLocation() {
                    return location;
                }

                /**
                 * Sets the value of the location property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLocation(String value) {
                    this.location = value;
                }

                /**
                 * Gets the value of the contact property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getContact() {
                    return contact;
                }

                /**
                 * Sets the value of the contact property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setContact(String value) {
                    this.contact = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="telephone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="education" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="qualifications" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="jobType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="desiredPosition" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="references" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="motivation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "address",
        "telephone",
        "email",
        "education",
        "language",
        "qualifications",
        "jobType",
        "desiredPosition",
        "references",
        "motivation"
    })
    public static class CvInfo {

        @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
        protected String name;
        @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
        protected String address;
        @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
        protected String telephone;
        @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
        protected String email;
        @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
        protected String education;
        @XmlElement(namespace = "http://namespace.profile.com/ns/profile")
        protected List<String> language;
        @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
        protected String qualifications;
        @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
        protected String jobType;
        @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
        protected String desiredPosition;
        @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
        protected String references;
        @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
        protected String motivation;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the address property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddress() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddress(String value) {
            this.address = value;
        }

        /**
         * Gets the value of the telephone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTelephone() {
            return telephone;
        }

        /**
         * Sets the value of the telephone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTelephone(String value) {
            this.telephone = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmail(String value) {
            this.email = value;
        }

        /**
         * Gets the value of the education property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEducation() {
            return education;
        }

        /**
         * Sets the value of the education property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEducation(String value) {
            this.education = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the language property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLanguage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getLanguage() {
            if (language == null) {
                language = new ArrayList<String>();
            }
            return this.language;
        }

        /**
         * Gets the value of the qualifications property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQualifications() {
            return qualifications;
        }

        /**
         * Sets the value of the qualifications property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQualifications(String value) {
            this.qualifications = value;
        }

        /**
         * Gets the value of the jobType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJobType() {
            return jobType;
        }

        /**
         * Sets the value of the jobType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJobType(String value) {
            this.jobType = value;
        }

        /**
         * Gets the value of the desiredPosition property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesiredPosition() {
            return desiredPosition;
        }

        /**
         * Sets the value of the desiredPosition property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesiredPosition(String value) {
            this.desiredPosition = value;
        }

        /**
         * Gets the value of the references property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReferences() {
            return references;
        }

        /**
         * Sets the value of the references property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReferences(String value) {
            this.references = value;
        }

        /**
         * Gets the value of the motivation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMotivation() {
            return motivation;
        }

        /**
         * Sets the value of the motivation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMotivation(String value) {
            this.motivation = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="empName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="companyWorked" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="workedAtComId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="workedAt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "empName",
        "companyWorked"
    })
    public static class EmpRecord {

        @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
        protected String empName;
        @XmlElement(namespace = "http://namespace.profile.com/ns/profile")
        protected List<Profile.EmpRecord.CompanyWorked> companyWorked;

        /**
         * Gets the value of the empName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmpName() {
            return empName;
        }

        /**
         * Sets the value of the empName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmpName(String value) {
            this.empName = value;
        }

        /**
         * Gets the value of the companyWorked property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the companyWorked property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCompanyWorked().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Profile.EmpRecord.CompanyWorked }
         * 
         * 
         */
        public List<Profile.EmpRecord.CompanyWorked> getCompanyWorked() {
            if (companyWorked == null) {
                companyWorked = new ArrayList<Profile.EmpRecord.CompanyWorked>();
            }
            return this.companyWorked;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="workedAtComId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="workedAt" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "workedAtComId",
            "workedAt",
            "duration",
            "year",
            "position"
        })
        public static class CompanyWorked {

            @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
            protected String workedAtComId;
            @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
            protected String workedAt;
            @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
            protected String duration;
            @XmlElement(namespace = "http://namespace.profile.com/ns/profile")
            protected int year;
            @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
            protected String position;

            /**
             * Gets the value of the workedAtComId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWorkedAtComId() {
                return workedAtComId;
            }

            /**
             * Sets the value of the workedAtComId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWorkedAtComId(String value) {
                this.workedAtComId = value;
            }

            /**
             * Gets the value of the workedAt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWorkedAt() {
                return workedAt;
            }

            /**
             * Sets the value of the workedAt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWorkedAt(String value) {
                this.workedAt = value;
            }

            /**
             * Gets the value of the duration property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDuration() {
                return duration;
            }

            /**
             * Sets the value of the duration property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDuration(String value) {
                this.duration = value;
            }

            /**
             * Gets the value of the year property.
             * 
             */
            public int getYear() {
                return year;
            }

            /**
             * Sets the value of the year property.
             * 
             */
            public void setYear(int value) {
                this.year = value;
            }

            /**
             * Gets the value of the position property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPosition() {
                return position;
            }

            /**
             * Sets the value of the position property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPosition(String value) {
                this.position = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="studentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="university" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="program" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="issueDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="gpa" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *         &lt;element name="courses">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="course" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="code">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;pattern value="[A-Z][A-Z][0-9][0-9][0-9][0-9]"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="credits" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                             &lt;element name="grade" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "studentName",
        "university",
        "program",
        "issueDate",
        "gpa",
        "courses"
    })
    public static class Transcript {

        @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
        protected String studentName;
        @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
        protected String university;
        @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
        protected String program;
        @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar issueDate;
        @XmlElement(namespace = "http://namespace.profile.com/ns/profile")
        protected BigDecimal gpa;
        @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
        protected Profile.Transcript.Courses courses;

        /**
         * Gets the value of the studentName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStudentName() {
            return studentName;
        }

        /**
         * Sets the value of the studentName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStudentName(String value) {
            this.studentName = value;
        }

        /**
         * Gets the value of the university property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUniversity() {
            return university;
        }

        /**
         * Sets the value of the university property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUniversity(String value) {
            this.university = value;
        }

        /**
         * Gets the value of the program property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProgram() {
            return program;
        }

        /**
         * Sets the value of the program property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProgram(String value) {
            this.program = value;
        }

        /**
         * Gets the value of the issueDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getIssueDate() {
            return issueDate;
        }

        /**
         * Sets the value of the issueDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setIssueDate(XMLGregorianCalendar value) {
            this.issueDate = value;
        }

        /**
         * Gets the value of the gpa property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getGpa() {
            return gpa;
        }

        /**
         * Sets the value of the gpa property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setGpa(BigDecimal value) {
            this.gpa = value;
        }

        /**
         * Gets the value of the courses property.
         * 
         * @return
         *     possible object is
         *     {@link Profile.Transcript.Courses }
         *     
         */
        public Profile.Transcript.Courses getCourses() {
            return courses;
        }

        /**
         * Sets the value of the courses property.
         * 
         * @param value
         *     allowed object is
         *     {@link Profile.Transcript.Courses }
         *     
         */
        public void setCourses(Profile.Transcript.Courses value) {
            this.courses = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="course" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="code">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;pattern value="[A-Z][A-Z][0-9][0-9][0-9][0-9]"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="credits" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                   &lt;element name="grade" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "course"
        })
        public static class Courses {

            @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
            protected List<Profile.Transcript.Courses.Course> course;

            /**
             * Gets the value of the course property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the course property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCourse().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Profile.Transcript.Courses.Course }
             * 
             * 
             */
            public List<Profile.Transcript.Courses.Course> getCourse() {
                if (course == null) {
                    course = new ArrayList<Profile.Transcript.Courses.Course>();
                }
                return this.course;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="code">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;pattern value="[A-Z][A-Z][0-9][0-9][0-9][0-9]"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="credits" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *         &lt;element name="grade" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "code",
                "title",
                "credits",
                "grade"
            })
            public static class Course {

                @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
                protected String code;
                @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
                protected String title;
                @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
                protected BigDecimal credits;
                @XmlElement(namespace = "http://namespace.profile.com/ns/profile", required = true)
                protected String grade;

                /**
                 * Gets the value of the code property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCode() {
                    return code;
                }

                /**
                 * Sets the value of the code property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCode(String value) {
                    this.code = value;
                }

                /**
                 * Gets the value of the title property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTitle() {
                    return title;
                }

                /**
                 * Sets the value of the title property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTitle(String value) {
                    this.title = value;
                }

                /**
                 * Gets the value of the credits property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getCredits() {
                    return credits;
                }

                /**
                 * Sets the value of the credits property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setCredits(BigDecimal value) {
                    this.credits = value;
                }

                /**
                 * Gets the value of the grade property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGrade() {
                    return grade;
                }

                /**
                 * Sets the value of the grade property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGrade(String value) {
                    this.grade = value;
                }

            }

        }

    }

}
